---

- hosts: localhost
  become: yes
  vars:
    auth:
      kind: "serviceaccount"
      file: "files/serviceaccount.pem"
    vm:
      project: "techipool"
      region: "us-central1"
      zone: "a"
      type: "e2-medium"
      os: "projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230428"
      disk_size: 20
      nodes:
        - name: "techipool-controlplane"
          internal_ip: "10.128.0.3"
        - name: "techipool-worker"
          internal_ip: "10.128.0.6"
  tasks:
    - name: Basic template example  
      template:  
        src: example1.j2  
        dest: /home/knoldus/Documents/Ansible/output.txt

    - name: Create root disks for controlplane
      ansible.builtin.uri:
      url: "https://www.googleapis.com/compute/v1/projects/{{ vm.project }}/zones/{{ vm.region }}-{{ vm.zone }}/instances"
      method: POST
      body_format: json
      status_code: [200, 202]
      return_content: true
      headers:
        Content-Type: application/json
        Authorization: Bearer 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
      register: vm