---

- hosts: localhost
  become: yes
  vars_files:
    - vars/vars.yaml
  tasks:
    - include_tasks: tasks/vm_provisioning.yaml
    #- include_tasks: tasks/create_user.yaml
    #- include_tasks: tasks/debug.yaml
