---

- name: Get ip
  ansible.builtin.uri:
    url: 'https://ifconfig.me/ip'
    method: GET
    return_content: true
  register: getIP

- name: Debug
  debug:
    var: ansible_default_ipv4.address
  when: ansible_hostname == 'controlplane'