---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force --cri-socket=/var/run/{{ container_runtime }}/{{ container_runtime }}.sock"
  register: reset_cluster

- name: Run init kubeadm
  shell: |
    kubeadm init --service-cidr {{ service_cidr }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --token {{ token }} \
                 --apiserver-advertise-address {{ master_ip }} \
                 --cri-socket=/var/run/{{ container_runtime }}/{{ container_runtime }}.sock
  args:
    executable: /bin/bash
  register: init_cluster

- name: Log the init results
  shell:  "{{ init_cluster }} > files/init_cluster.log"

- name: Copy kubernetes config directory
  file:
    path: "/home/rivan/.kube/"
    state: directory
  become_user: "{{ansible_user}}"

- name: Copy admin.conf to Home directory
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/rivan/.kube/config"
    owner: "rivan"
    group: "rivan"
    mode: 0755
  when: init_cluster is succeeded