---

#- name: Run the equivalent of "apt update" as a separate step
#  ansible.builtin.apt:
#    update_cache: yes
#
#- name: Allow everything and disable UFW
#  community.general.ufw:
#    state: disabled
#
#- name: Run command disable swap with bash shell
#  shell: swapoff -a
#  args:
#    executable: /bin/bash
#  become: true
#
#- name: Disable SWAP in fstab since kubernetes can't work with swap enabled
#  replace:
#    path: /etc/fstab
#    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
#    replace: '# \1'
#
#- name: Add the overlay module
#  community.general.modprobe:
#    name: overlay
#    state: present
#
#- name: Add the br_netfilter module
#  community.general.modprobe:
#    name: br_netfilter
#    state: present
#
#- name: Run command update sysctl settings for Kubernetes networking with bash shell
#  shell: |
#    tee /etc/sysctl.d/kubernetes.conf<<EOF
#    net.bridge.bridge-nf-call-ip6tables = 1
#    net.bridge.bridge-nf-call-iptables = 1
#    net.ipv4.ip_forward = 1
#    EOF
#
#    sysctl --system
#  args:
#    executable: /bin/bash  
#  become: true
#
#- name: Update repositories cache and install dependencie packages
#  ansible.builtin.apt:
#    name: ["gnupg2", "software-properties-common", "apt-transport-https", "ca-certificates", "curl"]
#    update_cache: yes
#
#- name: Add an docker Apt signing key, uses whichever key is at the URL
#  ansible.builtin.apt_key:
#    url: https://download.docker.com/linux/ubuntu/gpg
#    state: present

- name: Add docker repository to apt
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ vm_instance.os_codename }} stable"
    state: present
    filename: docker_repo
  loop: "{{ vm_json.results }}"
  loop_control:
    loop_var: vm_instance

- name: Add an kubeadm Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kubeadm repository to apt
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes.list

