---


- name: Basic vm template  
  template:  
    src: files/templates/vm.json.j2
    dest: "files/payloads/vm-{{ vm_node.name }}-{{ vm_node_idx }}.json"
  loop: "{{ vm.nodes }}"
  loop_control:
    loop_var: vm_node
    index_var: vm_node_idx
  register: vm_json

- name: Create worker and controlplane
  ansible.builtin.uri:
    url: "https://www.googleapis.com/compute/v1/projects/techipool/zones/us-central1-a/instances"
    method: POST
    src: "{{ vm_instance.dest }}"
    body_format: json
    status_code: [200, 202]
    return_content: true
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ auth.token }}"
  loop: "{{ vm_json.results }}"
  loop_control:
    loop_var: vm_instance
  register: vm

- debug: 
    var: vm

- debug: 
    var: vm_json.results

- name: Remove file (delete file)
  ansible.builtin.file:
    path: "{{ vm_instance.dest }}"
    state: absent
  loop: "{{ vm_json.results }}"
  loop_control:
    loop_var: vm_instance

- name: Basic hosts template  
  template:  
    src: files/templates/hosts.j2
    dest: "hosts"
  
- name: Append group on inventory
  ansible.builtin.blockinfile:
    path: hosts
    insertafter: EOF
    block: | 
      
      [k8snodes]
      
- name: Append list target on inventory
  ansible.builtin.lineinfile:
    path: hosts
    insertafter: \[k8snodes\]
    line: "{{ vm_instance.vm_node.name }} ansible_host={{ vm_instance.vm_node.internal_ip }} ansible_user=rivan ansible_ssh_private_key_file=\"files/ssh/gcloud.pem\" ansible_connection=ssh ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_python_interpreter=\"/usr/bin/python3\""
  loop: "{{ vm_json.results }}"
  loop_control:
    loop_var: vm_instance